import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from "@/lib/auth"
import prisma from '@/lib/prisma'
import crypto from 'crypto';

export async function POST(request) {
  try {
    // Step 1 — Make sure user is logged in
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json(
        { error: 'You must be logged in' },
        { status: 401 }
      )
    }

    // Step 2 — Read the request body
    const body = await request.json()
    const { name, description, clientName, clientEmail } = body

    // Step 3 — Validate required fields
    if (!name || !clientName || !clientEmail) {
      return NextResponse.json(
        { error: 'Name, client name and client email are required' },
        { status: 400 }
      )
    }

    // Step 4 — Create project AND client in one transaction
    const project = await prisma.project.create({
      data: {
        name,
        description: description || null,
        userId: session.user.id,  // link to logged in user
        githubWebhookSecret: crypto.randomBytes(32).toString('hex'),

        // Create the client at the same time
        // Prisma handles the relationship automatically
        client: {
          create: {
            name: clientName,
            email: clientEmail.toLowerCase(),
            // magicToken is auto-generated by @default(cuid()) in schema
          }
        }
      },
      include: {
        client: true // return the created client in response
      }
    })

    return NextResponse.json(project, { status: 201 })

  } catch (error) {
    console.error('Create project error:', error)
    return NextResponse.json(
      { error: 'Something went wrong' },
      { status: 500 }
    )
  }
}
